# Generated by Django 3.1.7 on 2021-03-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='basePrice',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
