# Generated by Django 3.1.7 on 2021-03-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_auto_20210324_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='basePrice',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
