# Generated by Django 3.1.7 on 2021-03-25 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_auto_20210324_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
    ]
