# Generated by Django 3.1.7 on 2021-03-30 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0020_checkout_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='user',
        ),
    ]
